# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
https://api.xmltime.com/dialcode?accesskey=wJG5rRMFxD&expires=2020-07-16T09%3A13%3A44%2B00%3A00&signature=QNJF9yYjviDRwIAeMrhx8iUi7t8%3D&version=3&out=xml&prettyprint=1&fromid=179&toid=136&number=918008090413&locinfo=1&geo=1&time=1&verbosetime=1&tz=1
