sudo: required
dist: trusty
language: bash
services: docker
env:
  matrix:
    - TARGET_OS=linux TARGET_ARCH=amd64 TARGETS="make validate coverage-send"
    - TARGET_OS=darwin TARGET_ARCH=amd64 TARGETS="cross"
    - TARGET_OS=windows TARGET_ARCH=amd64 TARGETS="cross"
script: USE_CONTAINER=true make "$TARGETS"
