cache:
  directories:
  - resources
  - node_modules

before_install:
  - brew unlink node
  - brew update
  - brew install homebrew/versions/node4-lts

script:
  - npm install
  - npm test
  - '[ "${TRAVIS_OS_NAME}" = "linux" ] && npm test || false'
  - '[ "${TRAVIS_OS_NAME}" = "linux" && "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run integration || false'
  - '[ "${TRAVIS_OS_NAME}" = "osx" && "${TRAVIS_PULL_REQUEST}" = "false" ] && ./ci/release || false'

os:
  - osx
  - linux
