language: node_js
node_js:
  - "0.10"

sudo: false

cache:
  - resources
  - node_modules

after_success:
  - which ./node_modules/coveralls/bin/coveralls.js && cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
