cache:
  directories:
  - resources
  - node_modules

before_install:
  - brew update
  - brew unlink node
  - brew install homebrew/versions/node4-lts

script:
  - npm install
  - npm test

after_script:
  - bash -c "$AFTER_SCRIPT"

os:
  - osx
