cache:
  directories:
  - resources
  - node_modules

before_install:
  - brew unlink node
  - brew update
  - brew install homebrew/versions/node4-lts

script:
  - npm install
  - npm test
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run integration || false'

after_script:
  - echo $KEY_CONTENT > ~/Library/Keychains/keychain.keychain
  - security unlock-keychain -p "$KEY_SECRET" keychain.keychain
  - npm run release

os:
  - osx
