cache:
  directories:
  - node_modules

install:
  - ./ci/install

script:
  - npm install
  - npm test
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run integration || false'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./ci/release || false'

matrix:
  include:
     - os: linux
       services:
         - docker
       language: node_js
       node_js:
         - "4.1"
    - os: osx
      language: generic

