cache:
  directories:
  - resources
  - node_modules

before_install:
  - brew unlink node
  - brew update
  - brew install homebrew/versions/node4-lts

script:
  - npm install
  - npm test
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run integration || false'

os:
  - osx
