name: Docker
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
incremental: true
permalink: pretty
safe: false
lsi: false
url: https://docs.docker.com

gems:
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-seo-tag

webrick:
  headers:
    Cache-Control: 600

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: docs
      archiveserver: "http://54.71.194.30"
  -
    scope:
      path: "datacenter/dtr/2.0"
    values:
      hide_from_sitemap: true
      dtr_latest: 2.1
  -
    scope:
      path: "datacenter/ucp/1.1"
    values:
      hide_from_sitemap: true
      ucp_latest: 2.0
  -
    scope:
      path: "apidocs/v1.3.3"
    values:
      hide_from_sitemap: true
  -
    scope:
      path: "apidocs/v1.4.0"
    values:
      hide_from_sitemap: true
  -
    scope:
      path: "apidocs/v2.0.0"
    values:
      hide_from_sitemap: true
  -
    scope:
      path: "apidocs/v2.0.1"
    values:
      hide_from_sitemap: true
