environment:
  GOPATH: c:\gopath
  SIGNTOOLPATH: C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin

clone_folder: c:\gopath\src\github.com\docker\pinata

before_build:
  - cd win/

build_script:
  - ps: ./please.ps1 AppVeyor

after_build:
  - cd ..
  - ps: >
      copy .\win\build\InstallDocker.msi InstallDocker.msi

artifacts:
  - path: win/build/InstallDocker.msi
  - path: win/TestResults/*.xml
  - path: InstallDocker.msi

test: off

configuration: Release

before_deploy:
  - ps: >
      if ($env:appveyor_pull_request_number -gt 0) {
        git fetch -q origin +refs/pull/$env:appveyor_pull_request_number/head
        $env:commit=(git rev-parse FETCH_HEAD)
      } else {
        $env:commit=$env:appveyor_repo_commit
      }
      true;

deploy:
  - provider: S3
    bucket: pinata-ci
    access_key_id: $(pinata_aws_key)
    secret_access_key: $(pinata_aws_secret)
    folder: $(commit)
    artifact: InstallDocker.msi
    on:
      appveyor_repo_tag: false
  - provider: S3
    bucket: pinata-ci
    access_key_id: $(pinata_aws_key)
    secret_access_key: $(pinata_aws_secret)
    folder: $(appveyor_repo_tag_name)
    artifact: InstallDocker.msi
    on:
      appveyor_repo_tag: true

