# Current project roles
[Roles]

    [Roles.bdfl]

    person = "shykes"

    [Roles."Chief Architect"]

    person = "shykes"

    text = """
The chief architect is responsible for the overall integrity of the technical architecture
across all subsystems, and the consistency of APIs and UI.

Changes to UI, public APIs and overall architecture (for example a plugin system) must
be approved by the chief architect.
"""

    [Roles."Chief Maintainer"]

    person = "crosbymichael"

    text = """
The chief maintainer is responsible for all aspects of quality for the project including
code reviews, usability, stability, security, performance, etc.
The most important function of the chief maintainer is to lead by example. On the first
day of a new maintainer, the best advice should be "follow the C.M.'s example and you'll
be fine".
"""

    [Roles."Community Manager"]

    person = "theadactyl"

    text = """
The community manager is responsible for serving the project community, including users,
contributors and partners. This involves:
    - facilitating communication between maintainers, contributors and users
    - organizing contributor and maintainer events
    - helping new contributors get involved
    - anything the project community needs to be successful

The community manager is a point of contact for any contributor who has questions, concerns
or feedback about project operations.
"""


