name: deploy website to netlify

on: pull_request

jobs:
  build-static-page:
    name: build
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: '1'
    steps:
      - name: print docker info
        run: docker version && docker info
      - uses: actions/checkout@v2
      - name: build image
        run: docker build --build-arg=ENABLE_ARCHIVES=false --target=current -t documentation:latest .
      - name: copy static files locally
        run: docker run -v ${PWD}:/output documentation:latest cp -r /usr/share/nginx/html /output/_site
      - name: check if secrets are well defined
        # not really a secret
        run: echo "${{ secrets.NETLIFY_ACCOUNT_SLUG }}"
      - name: deploy to netlify
        uses: ./.github/actions/netlify-deploy
        id: netlify_deploy
        with:
          NETLIFY_ACCOUNT_SLUG: ${{ secrets.NETLIFY_ACCOUNT_SLUG }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_DIRECTORY: _site
          NETLIFY_SITE_NAME: "${{ github.repository }}/${{ github.head_ref }}"
      - name: notify website is live
        uses: ./.github/actions/create-status-check
        with:
          SITE_URL: ${{ steps.netlify_deploy.outputs.site_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_TOKEN: ${{ github.token }}
